### ISSUE TITLE
Data

### ISSUE THREAD

**Issue by TopGun666** [JimmyJiang666/Similarity-Search-Using-LSH#1]
Hi Jimmy,

Thanks for your work. Could you provide the `data.txt` or an example of the form of `data.txt`?

Regards,

Will

**Comment by JimmyJiang666** [comment]
Here you go!
 data.zip
<https://drive.google.com/file/d/1YE1Zz5-NKQFV7CafAoJUQ684Q44Nc7Q2/view?usp=drive_web>


On Sun, Nov 8, 2020 at 11:51 AM Username <notifications@github.com> wrote:

> Hi Jimmy,
>
> Thanks for your work. Could you provide the data.txt or an example of the
> form of data.txt?
>
> Regards,
>
> Will
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub
> <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_JimmyJiang666_Similarity-2DSearch-2DUsing-2DLSH_issues_1&d=DwMCaQ&c=slrrB7dE8n7gBJbeO0g-IQ&r=t7-3zITb_77zn51RI9-AhQ&m=CluTVEz3pNsDUy9ZZgyCc-k0arNRgpZd9OS1QL6UAEU&s=aNEv4reWFmMVd1L24t9iLOTr8jpQOJuB6LyLBmQMmH0&e=>,
> or unsubscribe
> <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_notifications_unsubscribe-2Dauth_AKWH53TWD4KIQQZUDADUFBTSOZEZBANCNFSM4TOFECZA&d=DwMCaQ&c=slrrB7dE8n7gBJbeO0g-IQ&r=t7-3zITb_77zn51RI9-AhQ&m=CluTVEz3pNsDUy9ZZgyCc-k0arNRgpZd9OS1QL6UAEU&s=u9uP38uqZcYmS452iZcKJGfOSA3BxTJpOxvZ1yYSZEA&e=>
> .
>


-- 
*Muyan Jiang*

Mathematics & Computer Science, Class of 2022

Saadiyat Island
P.O. Box 129188
Abu Dhabi, United Arab Emirates
+971 561915297

**Comment by TopGun666** [comment]
Got it. Thanks a lot.

**Comment by TopGun666** [comment]
I have applied for access in google drive. Please give me permission. Thanks.

**Comment by JimmyJiang666** [comment]
https://drive.google.com/file/d/1YE1Zz5-NKQFV7CafAoJUQ684Q44Nc7Q2/view?usp=drivesdk

Can you access now?

On Mon, Nov 9, 2020 at 4:59 AM Username <notifications@github.com> wrote:

> I have applied for access in google drive. Please give me permission.
> Thanks.
>
> —
> You are receiving this because you commented.
>
>
> Reply to this email directly, view it on GitHub
> <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_JimmyJiang666_Similarity-2DSearch-2DUsing-2DLSH_issues_1-23issuecomment-2D723697761&d=DwMCaQ&c=slrrB7dE8n7gBJbeO0g-IQ&r=t7-3zITb_77zn51RI9-AhQ&m=v_Mjg-kz87Cvu7wf5e9JbiG3t0pocA5kwG9KmgI-umM&s=wqFm96TMQyMlzrVelFOFq-KO1dTBwQZxYc1BQzyAd7Q&e=>,
> or unsubscribe
> <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_notifications_unsubscribe-2Dauth_AKWH53SURJOFTMLUBD7AM73SO45FXANCNFSM4TOFECZA&d=DwMCaQ&c=slrrB7dE8n7gBJbeO0g-IQ&r=t7-3zITb_77zn51RI9-AhQ&m=v_Mjg-kz87Cvu7wf5e9JbiG3t0pocA5kwG9KmgI-umM&s=Xi55gZwN1dTnluln3wi1XEUqsp9SUoh9k5j8qcdQMHE&e=>
> .
>
-- 
*Muyan Jiang*

Mathematics & Computer Science, Class of 2022

Saadiyat Island
P.O. Box 129188
Abu Dhabi, United Arab Emirates
+971 561915297

**Comment by TopGun666** [comment]
<img width="682" alt="image" src="https://user-images.githubusercontent.com/23215825/98507284-3c7b0280-2298-11eb-8940-46a51178361b.png">
